server.port: 8082

domain.uri: 52.87.220.41

signing.key: 345345fsdgsf5345

tracer.property: "I AM THE DEFAULT"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://mysqldb.c4v3j9tgecmv.us-east-1.rds.amazonaws.com:3306/itemsharing"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}3c0309574137fe472814543612b2866aaf6c103271478299a35379c85a6f1dfe"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect:
     "org.hibernate.dialect.MySQL5Dialect"
spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        inboundUserChanges:
          destination: userChangeTopic
          content-type: application/json
          group: userGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
        input:
          destination: userChangeTopic
          content-type: application/json
          group: userGroup
# security:
#   basic:
#     enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://${domain.uri}:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG

security:
 oauth2:
  resource:
    userInfoUri: http://${domain.uri}:8901/user

redis.server: "localhost"
redis.port: "6379"