server.port: 8081

signing.key: 345345fsdgsf5345

tracer.property: "I AM THE DEFAULT"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/itemsharing"
spring.datasource.username: "root"
spring.datasource.password: "Rochester24"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect:
     "org.hibernate.dialect.MySQL5Dialect"
spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        output:
            destination:  userChangeTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      
# security:
#   basic:
#     enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://52.87.220.41:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG

security:
 oauth2:
  resource:
    userInfoUri: http://52.87.220.41:8901/user


